/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddToFavoriteButton: typeof import('./../src/components/SVGIcons/AddToFavoriteButton.vue')['default']
    AppToolBar: typeof import('./../src/components/AppToolBar.vue')['default']
    AscendingSorting: typeof import('./../src/components/SVGIcons/AscendingSorting.vue')['default']
    BackButton: typeof import('./../src/components/BackButton.vue')['default']
    BackButtonIcon: typeof import('./../src/components/SVGIcons/BackButtonIcon.vue')['default']
    BreedsInfo: typeof import('./../src/views/Breeds/components/BreedsInfo.vue')['default']
    copy: typeof import('./../src/components/SVGIcons/LogLikeIcon copy.vue')['default']
    DecsendingSorting: typeof import('./../src/components/SVGIcons/DecsendingSorting.vue')['default']
    DislikeIcon: typeof import('./../src/components/SVGIcons/DislikeIcon.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FavoritesIcon: typeof import('./../src/components/SVGIcons/FavoritesIcon.vue')['default']
    Filters: typeof import('./../src/components/Filters.vue')['default']
    Grid: typeof import('./../src/components/Grid.vue')['default']
    GridModule: typeof import('./../src/components/GridModule.vue')['default']
    LikesIcon: typeof import('./../src/components/SVGIcons/LikesIcon.vue')['default']
    LogAddedToFavoriteIcon: typeof import('./../src/components/SVGIcons/LogAddedToFavoriteIcon.vue')['default']
    LogDislikeIcon: typeof import('./../src/components/SVGIcons/LogDislikeIcon.vue')['default']
    LogLikeIcon: typeof import('./../src/components/SVGIcons/LogLikeIcon.vue')['default']
    Logo: typeof import('./../src/components/SVGIcons/Logo.vue')['default']
    NoItemsFound: typeof import('./../src/components/NoItemsFound.vue')['default']
    RefreshIcon: typeof import('./../src/components/SVGIcons/RefreshIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./../src/components/SVGIcons/SearchIcon.vue')['default']
    UserLog: typeof import('./../src/components/UserLog.vue')['default']
    VotingAddedToFavorite: typeof import('./../src/components/SVGIcons/VotingAddedToFavorite.vue')['default']
    VotingAddToFavorite: typeof import('./../src/components/SVGIcons/VotingAddToFavorite.vue')['default']
    VotingDIslikeIcon: typeof import('./../src/components/SVGIcons/VotingDIslikeIcon.vue')['default']
    VotingLikeIcon: typeof import('./../src/components/SVGIcons/VotingLikeIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
