/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddToFavoriteButton: typeof import('@/components/svg-icons/AddToFavoriteButton.vue')['default']
    AppToolBar: typeof import('./../src/components/AppToolBar.vue')['default']
    AscendingSorting: typeof import('@/components/svg-icons/AscendingSorting.vue')['default']
    BackButton: typeof import('./../src/components/BackButton.vue')['default']
    BackButtonIcon: typeof import('@/components/svg-icons/BackButtonIcon.vue')['default']
    BreedsInfo: typeof import('@/views/breeds/components/BreedsInfo.vue')['default']
    DecsendingSorting: typeof import('@/components/svg-icons/DecsendingSorting.vue')['default']
    DislikeIcon: typeof import('@/components/svg-icons/DislikeIcon.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FavoritesIcon: typeof import('@/components/svg-icons/FavoritesIcon.vue')['default']
    Filters: typeof import('./../src/components/Filters.vue')['default']
    Grid: typeof import('./../src/components/Grid.vue')['default']
    GridModule: typeof import('./../src/components/GridModule.vue')['default']
    LikesIcon: typeof import('@/components/svg-icons/LikesIcon.vue')['default']
    LogAddedToFavoriteIcon: typeof import('@/components/svg-icons/LogAddedToFavoriteIcon.vue')['default']
    LogDislikeIcon: typeof import('@/components/svg-icons/LogDislikeIcon.vue')['default']
    LogLikeIcon: typeof import('@/components/svg-icons/LogLikeIcon.vue')['default']
    Logo: typeof import('@/components/svg-icons/Logo.vue')['default']
    NoItemsFound: typeof import('./../src/components/NoItemsFound.vue')['default']
    RefreshIcon: typeof import('@/components/svg-icons/RefreshIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('@/components/svg-icons/SearchIcon.vue')['default']
    UserLog: typeof import('./../src/components/UserLog.vue')['default']
    VotingAddedToFavorite: typeof import('@/components/svg-icons/VotingAddedToFavorite.vue')['default']
    VotingAddToFavorite: typeof import('@/components/svg-icons/VotingAddToFavorite.vue')['default']
    VotingDIslikeIcon: typeof import('@/components/svg-icons/VotingDIslikeIcon.vue')['default']
    VotingLikeIcon: typeof import('@/components/svg-icons/VotingLikeIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
