/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppToolBar: typeof import('./../src/components/AppToolBar.vue')['default']
    AscendingSorting: typeof import('./../src/components/AscendingSorting.vue')['default']
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    BackButton: typeof import('./../src/components/BackButton.vue')['default']
    BreedsFilter: typeof import('./../src/components/BreedsFilter.vue')['default']
    BreedsSearch: typeof import('./../src/components/BreedsSearch.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    DecsendingSorting: typeof import('./../src/components/DecsendingSorting.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExampleViewComponent: typeof import('./../src/views/example-view/components/ExampleViewComponent.vue')['default']
    FF: typeof import('./../src/components/FF.vue')['default']
    GaleryToolbar: typeof import('./../src/components/GaleryToolbar.vue')['default']
    Grid: typeof import('./../src/components/Grid.vue')['default']
    GridItem: typeof import('./../src/components/GridItem.vue')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    ImageLimit: typeof import('./../src/components/ImageLimit.vue')['default']
    Logo: typeof import('./../src/components/Logo.vue')['default']
    Navigation: typeof import('@/views/Navigation/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserLog: typeof import('./../src/components/UserLog.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
